# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gta4xlwifi/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),gta4xlwifi)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-P610,d6b7f690a5662efc85514b456122965faf527db4)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-P610,e10c3fa03da157f6f8d8370230d16f6038b67384)
$(call add-radio-file-sha1-checked,radio/models,0a5c3b2cef8f0c09b09f80363601f16491824a89)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-P610,dbc39d61a69eb31bfab277ec3c8deb1c4101ffaa)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-P610,64479427dc71e0292ff77639ab569512a588406d)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-P610,bd8175a5be0d25a80472994f35886024d6dff0c8)
$(call add-radio-file-sha1-checked,radio/version_SM-P610,f9028f6cb22887987551ec2df84c3847ac5ec6b4)

endif
